name: Compile and release for Windows

on:
  workflow_dispatch:
    inputs:
     tag:
       description: 'Release tag name'
       required: true
       type: string

jobs:
  compile:
    uses: ./.github/workflows/compile.yml

  release:
    runs-on: ubuntu-latest
    needs: compile
    permissions:
      contents: write

    steps:
    - name: Get compilation artifacts
      uses: actions/download-artifact@v4

    - name: Archive files
      run: |
        cd ${{ needs.compile.outputs.project-name }}-windows-latest
        7z a -mmt4 -mx9 ../${{ needs.compile.outputs.project-name }}-Windows.7z ${{ needs.compile.outputs.project-name }}.exe

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        name: Executables
        tag_name: ${{ inputs.tag }}
        files: ${{ needs.compile.outputs.project-name }}-Windows.7z
        make_latest: true
